### PR TITLE
nix local development

### PR DESCRIPTION
**Pull request by ricardo-valero**
- flakes
- direnv
- devenv

### CODE REVIEW

**Comment by Tylopilus** [comment]
What is this for?

**Comment by ricardo-valero** [comment]
This is tailored for Nix users and is limited to local development. 

Nix simplifies dependency management with reproducible builds, eliminating the need to install Node.js or MySQL directly on your local machine.

direnv facilitates the loading of the Nix environment, while devenv allows configuration of processes and services. Here, it’s used to add the MySQL service. 

Unlike Docker, which offers _repeatable_ builds, Nix not only ensures reproducibility but also provides isolation without the container overhead, resulting in a resource-friendly solution.

While I’m not advocating exclusive use, I wanted to share an alternative.

Recognizing that this might introduce additional elements to the repository, it offers an option for those interested.

This setup reflects how I personally configured my local development environment to begin exploring the repository.

**Comment by bautistaaa** [comment]
im leaning towards closing this

thoughts @Hacksore @QuiiBz

**Comment by Hacksore** [comment]
Yes nix is not worth supporting, pease close @bautistaaa

**Pull request closed without merging**
