### PR TITLE
feat: integrate million auto mode

### PR DESCRIPTION
**Pull request by AnitKrJha**
Resolves https://github.com/aidenybai/million/issues/556
/claim  https://github.com/aidenybai/million/issues/556

added million automatic mode to admin and web apss for typehero

### CODE REVIEW

**Comment by jhechtf** [comment]
In testing this locally I run into a similar problem as the other pr: builds are broken and dev mode no longer functions, as such I'm hesitant to approve this. 

CC: @bautistaaa

**Comment by AnitKrJha** [comment]
@bautistaaa please look into this, and tell if any changes are needed!

**Comment by AnitKrJha** [comment]
@jhechtf can you help me to figure out where do I get "EDGE_CONFIG" env variable from?

**Comment by QuiiBz** [comment]
Closing as duplicate - dev and builds no longer work as expected and we're looking into it with Aiden here: https://github.com/bautistaaa/typehero/pull/430

**Pull request closed without merging**
