### PR TITLE
Feat/a11y focus and focus visible states

### PR DESCRIPTION
**Pull request by laureanray**
I think a11y is a moving target as we create more features/components. I will open the PR for now and maybe just do a follow up if I found new elements to add the proper classes. 

We should probably keep #243 open for tracking. 

# Preview:
Note: I have used "force element state" to apply the `:focus` and `:focus-visible` pseudoclasses. 

On focus, the elements should look like the screenshot (obviously not at the same time) 

## Navigation
image

## Features
image

## Community
image

## Explore
image
image

## Other 
- This should also fix some elements being focused twice because of nested focus-able elements like `<Link>` and `<Button>` nested.
- Removed shadcn components `focus-visible:ring-offset-2`

### CODE REVIEW

**Comment by PickleNik** [comment]
@laureanray I fixed a couple conflicts I introduced in main, pls pull, sorry, thanks

**Comment by PickleNik** [comment]
This is huge, thanks @laureanray.

I wanna run it thru my local to checkout first but then I'll approb and merge soon as I can 👍

**Comment by PickleNik** [comment]
created a separate issue for some related but out-of-scope stuff if u wanna take it #502

**Comment by laureanray** [comment]
> created a separate issue for some related but out-of-scope stuff if u wanna take it #502

Yes, you can assign it to me.

**Pull request merged**
