### PR TITLE
[#460] Fullscreen button stub

### LINKED ISSUE #460: fullscreen editor
Screenshot 2023-08-27 at 1 33 17 PM

### PR DESCRIPTION
**Pull request by Tylopilus**
Fixes #460

### CODE REVIEW

**Review by Hacksore — CHANGES_REQUESTED** [review]
Just need prettier to pass, can you run `pnpm checks:fix`

**Comment by typesafegh** [comment]
Done thanks!

**Comment by Tylopilus** [comment]
I ran prettier fix and should be good now. But I had to run it explicitly in the monaco-package.

**Review by PickleNik — APPROVED** [review]
LG™️

**Comment by PickleNik** [comment]
Prettier still fails

**Pull request merged**
