### PR TITLE
Explore card redesign closes #395

### LINKED ISSUE #395: Explore Cards design change
Screenshot 2023-08-22 at 10 01 16 PM
Screenshot 2023-08-22 at 10 01 47 PM

### PR DESCRIPTION
**Pull request by PickleNik**
closes #395 

https://github.com/bautistaaa/typehero/assets/31113245/f69cce51-5509-4f0c-8253-1a0c99d02765

### CODE REVIEW

**Comment by PickleNik** [comment]
the Extreme card is my fav

https://github.com/bautistaaa/typehero/assets/31113245/65b32d3f-0d45-4dae-8fda-d3c05db209ae

**Comment by PickleNik** [comment]
somebody pls find a better color for **Medium**s

**Comment by PickleNik** [comment]
best kind of PR
Screenshot 2023-08-24 at 12 48 59 AM

**Review by jhechtf — APPROVED** [review]
LGTM

**Comment by bautistaaa** [comment]
yes queen

**Comment by bautistaaa** [comment]
is mobile all good? curious what the next page looks like after clicking view more guess we’ll see after you merge

**Comment by PickleNik** [comment]
> is mobile all good? curious what the next page looks like after clicking view more guess we’ll see after you merge


https://github.com/bautistaaa/typehero/assets/31113245/b2aa0ffb-da7a-4c1f-a9b4-df6817a8804b

**Comment by PickleNik** [comment]
fixed the slug 

Screenshot 2023-08-24 at 1 34 19 AM

**Pull request merged**
