### PR TITLE
Add vercel toolbar to localhost for comments

### PR DESCRIPTION
**Pull request by Hacksore**
thanks @anthonyshew this is really cool!

image

### CODE REVIEW

**Comment by Hacksore** [comment]
So it's working with the dev server but not at build time, someone please offer some suggestions.

🙏

**Comment by Hacksore** [comment]
I can revive this one there are some docs or real world examples of how to use it 😬 

Just tag me when that happens here @anthonyshew

**Comment by Hacksore** [comment]
We have talked more about this in discord and a patch package seems to work in a non-monorepo but in ours it explodes.

Discord: https://discord.gg/nextjs
Thread: https://discord.com/channels/752553802359505017/1145009379054207006

**Comment by Hacksore** [comment]
This works now thanks to help from @joulev ❤️.

So in order to use this you need to `vercel link` and configure for typehero app then start the dev server.

Once I get someone saying it works we can merge it!

**Review by QuiiBz — APPROVED** [review]
Confirmed that it works

**Pull request merged**
